name: CI-CD Manufacturer Project

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io/kkarri0119
  IMAGE_NAME: springboot-manufacturer-microservice
  GITHUB_SHA: ${{ github.sha || 'localtest001' }}
  KUBE_NAMESPACE: default

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    # --- Setup Java ---
    - name: Set up JDK 17
      if: github.actor != 'local'   # skip locally if Node is missing
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Install Maven (for local or container)
      run: |
        # no sudo needed inside act container
        apt-get update
        apt-get install -y maven

    # --- Build Spring Boot ---
    - name: Build Spring Boot Manufacturer Microservices
      run: mvn clean install

    # --- Docker Login (skip locally) ---
    - name: Log in to GitHub Container Registry
      if: github.actor != 'local'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: ghcr.io

    # --- Build and Push Docker Image ---
    - name: Build and Push Docker Image
      if: github.actor != 'local'
      run: |
        docker build -t $REGISTRY/$IMAGE_NAME:$GITHUB_SHA .
        docker push $REGISTRY/$IMAGE_NAME:$GITHUB_SHA
